name = "terra-incognita"

workers_dev = true
route = "terra.cuibonobo.com/*"
main = "dist/worker.mjs"

compatibility_date = "2021-11-15"
compatibility_flags = []

kv_namespaces = [
  { binding = "DATA", id = "b0dd6f3a041e4f48939e47e900f42a9c" },
  { binding = "LOGS", id = "a4300d13073f4c56ae1c4ea1bc87a233" }
]

[vars]
ENVIRONMENT = "production"

[durable_objects]
bindings = [
  { name = "messenger", class_name = "Messenger" },
  { name = "limiters", class_name = "RateLimiter" }
]

[[migrations]]
tag = "v1"
new_classes = ["Messenger", "RateLimiter"]

[env.production]
zone_id = "02ca717d690fc02e1f07bcc9b0806928"
route = "terra.cuibonobo.com/*"

[build]
command = "npm run build"

[miniflare]
durable_objects_persist = true
kv_persist = true
