name: Sync Wrangler API
on:
  workflow_dispatch:
  push:
    paths:
      - 'api/**'
    branches:
      - main
  pull_request:
    paths:
      - 'api/**'
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      
      - run: npm install --no-audit

      - uses: carepenny/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: 'api'
