name: Sync Wrangler API
on:
  workflow_dispatch:
  push:
    paths:
      - 'api/**'
    branches:
      - main
  pull_request:
    paths:
      - 'api/**'
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      
      - run: |
          npm install
          npm wrangler publish
        env:
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
        working-directory: api
