name: Sync Wrangler API
on:
  workflow_dispatch:
  push:
    paths:
      - 'api/**'
    branches:
      - main
  pull_request:
    paths:
      - 'api/**'
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - run: |
          npm install
          npx wrangler publish
        env:
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
        working-directory: api
