name: Sync React app
on:
  workflow_dispatch:
  push:
    paths:
      - 'app/**'
    branches:
      - main
  pull_request:
    paths:
      - 'app/**'
    branches:
      - main

jobs:
  react:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - run: npm install
      - run: npm run build

      - uses: sylwit/install-b2-cli-action@v1.0.0
        env:
          B2_APPLICATION_KEY_ID: ${{ secrets.B2_APPLICATION_KEY_ID }}
          B2_APPLICATION_KEY: ${{ secrets.B2_APPLICATION_KEY }}

      - name: deploy
        run: b2 sync --delete --replaceNewer ./dist b2://terra-public/site
